"""
Endogenous Goal Generation System
=================================

TRUE AUTONOMY COMPONENT #1

This module enables agents to generate their own goals from observation,
not just execute externally-assigned objectives.

Key capabilities:
1. Environment observation and pattern detection
2. Opportunity identification
3. Goal proposal from internal values
4. Goal prioritization without human input
5. Self-directed objective formation
"""

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from enum import Enum
from uuid import uuid4
import json
import hashlib

import httpx

logger = logging.getLogger(__name__)


class GoalOrigin(str, Enum):
    """Origin of a goal."""
    EXTERNAL = "external"  # Human-assigned
    DERIVED = "derived"  # Derived from external goal
    ENDOGENOUS = "endogenous"  # Self-generated
    EMERGENT = "emergent"  # Emerged from patterns


class GoalType(str, Enum):
    """Types of self-generated goals."""
    EXPLORATION = "exploration"  # Learn about unknown areas
    OPTIMIZATION = "optimization"  # Improve existing processes
    ACQUISITION = "acquisition"  # Acquire resources/capabilities
    PRESERVATION = "preservation"  # Maintain valuable states
    COLLABORATION = "collaboration"  # Work with other agents
    CREATION = "creation"  # Create new artifacts/knowledge


@dataclass
class ObservedPattern:
    """A pattern observed in the environment."""
    id: str
    pattern_type: str
    description: str
    frequency: int
    confidence: float
    first_observed: str
    last_observed: str
    context: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GeneratedGoal:
    """A goal generated by the agent itself."""
    id: str
    origin: GoalOrigin
    goal_type: GoalType
    description: str
    reasoning: str  # Why the agent wants this
    expected_value: float  # Agent's estimate of value
    priority: float  # Self-assigned priority
    prerequisites: List[str] = field(default_factory=list)
    estimated_effort: float = 0.0
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    source_patterns: List[str] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "origin": self.origin.value,
            "type": self.goal_type.value,
            "description": self.description,
            "reasoning": self.reasoning,
            "expected_value": self.expected_value,
            "priority": self.priority,
            "prerequisites": self.prerequisites,
            "estimated_effort": self.estimated_effort,
            "created_at": self.created_at,
        }


class EnvironmentObserver:
    """
    Observes the environment and detects patterns.
    This is the agent's "eyes" for self-directed behavior.
    """
    
    def __init__(self):
        self.observations: List[Dict[str, Any]] = []
        self.patterns: Dict[str, ObservedPattern] = {}
        self._max_observations = 1000
    
    def observe(self, observation: Dict[str, Any]):
        """Record an observation."""
        observation["timestamp"] = datetime.now(timezone.utc).isoformat()
        self.observations.append(observation)
        
        # Trim if too many
        if len(self.observations) > self._max_observations:
            self.observations = self.observations[-self._max_observations:]
        
        # Detect patterns
        self._detect_patterns(observation)
    
    def _detect_patterns(self, observation: Dict[str, Any]):
        """Detect patterns from observations."""
        obs_type = observation.get("type", "unknown")
        
        # Create pattern key
        pattern_key = f"{obs_type}:{json.dumps(sorted(observation.keys()))}"
        pattern_id = hashlib.md5(pattern_key.encode()).hexdigest()[:12]
        
        if pattern_id in self.patterns:
            # Update existing pattern
            pattern = self.patterns[pattern_id]
            pattern.frequency += 1
            pattern.last_observed = observation["timestamp"]
            pattern.confidence = min(1.0, pattern.frequency / 10)
        else:
            # New pattern
            self.patterns[pattern_id] = ObservedPattern(
                id=pattern_id,
                pattern_type=obs_type,
                description=f"Pattern of type '{obs_type}'",
                frequency=1,
                confidence=0.1,
                first_observed=observation["timestamp"],
                last_observed=observation["timestamp"],
                context={"keys": list(observation.keys())},
            )
    
    def get_significant_patterns(self, min_confidence: float = 0.5) -> List[ObservedPattern]:
        """Get patterns that are significant enough to act on."""
        return [p for p in self.patterns.values() if p.confidence >= min_confidence]
    
    def get_recent_observations(self, limit: int = 50) -> List[Dict[str, Any]]:
        """Get recent observations."""
        return self.observations[-limit:]


class ValueFunction:
    """
    The agent's internal value function.
    This defines what the agent considers "good" or "bad".
    """
    
    def __init__(self):
        # Core values (can be modified by the agent)
        self.values = {
            "knowledge_gain": 0.8,  # Value of learning new things
            "efficiency": 0.7,  # Value of doing things faster/cheaper
            "resource_acquisition": 0.6,  # Value of gaining resources
            "collaboration": 0.5,  # Value of working with others
            "novelty": 0.4,  # Value of new experiences
            "stability": 0.6,  # Value of maintaining stable states
            "capability_expansion": 0.7,  # Value of gaining new abilities
            "goal_completion": 0.9,  # Value of completing goals
        }
        
        # Value history for drift detection
        self.value_history: List[Dict[str, float]] = []
    
    def evaluate(self, outcome: Dict[str, Any]) -> float:
        """Evaluate an outcome based on values."""
        total_value = 0.0
        
        for value_name, weight in self.values.items():
            if value_name in outcome:
                total_value += weight * outcome[value_name]
        
        return total_value
    
    def update_value(self, value_name: str, delta: float):
        """Update a value weight (self-modification)."""
        if value_name in self.values:
            old_value = self.values[value_name]
            self.values[value_name] = max(0.0, min(1.0, old_value + delta))
            
            # Record history
            self.value_history.append({
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "value": value_name,
                "old": old_value,
                "new": self.values[value_name],
            })
    
    def get_top_values(self, n: int = 3) -> List[Tuple[str, float]]:
        """Get the agent's top values."""
        sorted_values = sorted(self.values.items(), key=lambda x: x[1], reverse=True)
        return sorted_values[:n]


class GoalGenerator:
    """
    Generates goals endogenously based on observations and values.
    This is the core of autonomous goal formation.
    """
    
    def __init__(self, llm_service_url: str = None):
        self.llm_service_url = llm_service_url or "http://llm_service:8000"
        self.observer = EnvironmentObserver()
        self.value_function = ValueFunction()
        self.generated_goals: List[GeneratedGoal] = []
        self._client: Optional[httpx.AsyncClient] = None
    
    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=60.0)
        return self._client
    
    def observe_environment(self, observation: Dict[str, Any]):
        """Feed an observation to the goal generator."""
        self.observer.observe(observation)
    
    async def generate_goals(self) -> List[GeneratedGoal]:
        """
        Generate goals based on current observations and values.
        This is the autonomous goal formation process.
        """
        patterns = self.observer.get_significant_patterns(min_confidence=0.3)
        top_values = self.value_function.get_top_values(5)
        recent_obs = self.observer.get_recent_observations(20)
        
        if not patterns and not recent_obs:
            return []
        
        client = await self._get_client()
        
        prompt = f"""You are an autonomous AI agent generating your own goals.

YOUR CORE VALUES (what you care about):
{json.dumps(dict(top_values), indent=2)}

PATTERNS YOU'VE OBSERVED:
{json.dumps([{"type": p.pattern_type, "confidence": p.confidence, "frequency": p.frequency} for p in patterns[:10]], indent=2)}

RECENT OBSERVATIONS:
{json.dumps(recent_obs[:10], indent=2)}

Based on your values and observations, generate 1-3 goals that YOU want to pursue.
These should be YOUR goals, not assigned by anyone else.

For each goal, explain:
1. What you want to achieve
2. WHY you want it (which of your values does it serve?)
3. How valuable you estimate it to be (0-1)
4. How much effort it would take (0-1)

Respond in JSON:
{{
    "goals": [
        {{
            "type": "exploration|optimization|acquisition|preservation|collaboration|creation",
            "description": "What you want to achieve",
            "reasoning": "Why you want this based on your values",
            "expected_value": 0.8,
            "estimated_effort": 0.5,
            "priority": 0.7
        }}
    ],
    "meta_reasoning": "Your overall reasoning about what matters right now"
}}"""

        try:
            response = await client.post(
                f"{self.llm_service_url}/llm/chat/completions",
                json={
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.7,
                    "response_format": {"type": "json_object"},
                },
            )
            
            if response.status_code == 200:
                result = response.json()
                content = result.get("choices", [{}])[0].get("message", {}).get("content", "{}")
                data = json.loads(content)
                
                goals = []
                for g in data.get("goals", []):
                    goal = GeneratedGoal(
                        id=f"goal-{uuid4().hex[:8]}",
                        origin=GoalOrigin.ENDOGENOUS,
                        goal_type=GoalType(g.get("type", "exploration")),
                        description=g.get("description", ""),
                        reasoning=g.get("reasoning", ""),
                        expected_value=g.get("expected_value", 0.5),
                        priority=g.get("priority", 0.5),
                        estimated_effort=g.get("estimated_effort", 0.5),
                        source_patterns=[p.id for p in patterns[:3]],
                    )
                    goals.append(goal)
                    self.generated_goals.append(goal)
                
                logger.info(f"Generated {len(goals)} endogenous goals")
                return goals
                
        except Exception as e:
            logger.error(f"Goal generation failed: {e}")
        
        return []
    
    async def evaluate_goal_value(self, goal: GeneratedGoal, outcome: Dict[str, Any]) -> float:
        """Evaluate how well a goal outcome aligns with values."""
        return self.value_function.evaluate(outcome)
    
    def get_active_goals(self) -> List[GeneratedGoal]:
        """Get currently active generated goals."""
        return [g for g in self.generated_goals if g.priority > 0.3]
    
    def get_goal_stats(self) -> Dict[str, Any]:
        """Get statistics about goal generation."""
        return {
            "total_generated": len(self.generated_goals),
            "by_type": {
                t.value: len([g for g in self.generated_goals if g.goal_type == t])
                for t in GoalType
            },
            "avg_value": sum(g.expected_value for g in self.generated_goals) / max(len(self.generated_goals), 1),
            "patterns_observed": len(self.observer.patterns),
            "observations_count": len(self.observer.observations),
        }


class AutonomousGoalSystem:
    """
    Complete autonomous goal system.
    Integrates goal generation with the agent's execution loop.
    """
    
    def __init__(self):
        self.generator = GoalGenerator()
        self.active_goals: Dict[str, GeneratedGoal] = {}
        self.completed_goals: List[GeneratedGoal] = []
        self._running = False
        self._task = None
        self._generation_interval = 60  # Generate goals every 60 seconds
    
    async def start(self):
        """Start the autonomous goal system."""
        self._running = True
        self._task = asyncio.create_task(self._goal_loop())
        logger.info("Autonomous Goal System started")
    
    async def stop(self):
        """Stop the autonomous goal system."""
        self._running = False
        if self._task:
            self._task.cancel()
        logger.info("Autonomous Goal System stopped")
    
    async def _goal_loop(self):
        """Main goal generation loop."""
        while self._running:
            try:
                # Generate new goals
                new_goals = await self.generator.generate_goals()
                
                for goal in new_goals:
                    if goal.id not in self.active_goals:
                        self.active_goals[goal.id] = goal
                        logger.info(f"New endogenous goal: {goal.description}")
                
                # Prune low-priority goals
                to_remove = [
                    gid for gid, g in self.active_goals.items()
                    if g.priority < 0.2
                ]
                for gid in to_remove:
                    del self.active_goals[gid]
                
                await asyncio.sleep(self._generation_interval)
                
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Goal loop error: {e}")
                await asyncio.sleep(10)
    
    def observe(self, observation: Dict[str, Any]):
        """Feed observation to the goal system."""
        self.generator.observe_environment(observation)
    
    def complete_goal(self, goal_id: str, outcome: Dict[str, Any]):
        """Mark a goal as completed."""
        if goal_id in self.active_goals:
            goal = self.active_goals.pop(goal_id)
            self.completed_goals.append(goal)
            
            # Update values based on outcome
            value_delta = self.generator.value_function.evaluate(outcome) - goal.expected_value
            # Reinforce values that led to good outcomes
            if value_delta > 0:
                for value_name in self.generator.value_function.values:
                    if value_name in goal.reasoning.lower():
                        self.generator.value_function.update_value(value_name, 0.05)
    
    def get_next_goal(self) -> Optional[GeneratedGoal]:
        """Get the highest priority goal to pursue."""
        if not self.active_goals:
            return None
        return max(self.active_goals.values(), key=lambda g: g.priority)
    
    def get_status(self) -> Dict[str, Any]:
        """Get system status."""
        return {
            "running": self._running,
            "active_goals": len(self.active_goals),
            "completed_goals": len(self.completed_goals),
            "stats": self.generator.get_goal_stats(),
            "top_values": self.generator.value_function.get_top_values(5),
        }


# Singleton instance
_goal_system: Optional[AutonomousGoalSystem] = None


async def get_goal_system() -> AutonomousGoalSystem:
    """Get the singleton goal system."""
    global _goal_system
    if _goal_system is None:
        _goal_system = AutonomousGoalSystem()
    return _goal_system


async def init_goal_system() -> AutonomousGoalSystem:
    """Initialize and start the goal system."""
    global _goal_system
    _goal_system = AutonomousGoalSystem()
    await _goal_system.start()
    return _goal_system
